Fixes in config and on PXE_NIC settings

diff --git a/third-party/ironic/deploy/configmap-bin.yaml b/third-party/ironic/deploy/configmap-bin.yaml
--- a/third-party/ironic/deploy/configmap-bin.yaml
+++ b/third-party/ironic/deploy/configmap-bin.yaml
@@ -86,6 +86,22 @@ data:
   ironic-conductor-init.sh: |
     #!/bin/bash
     set -ex
+
+    if [ "x" == "x${PXE_NIC}" ]; then
+        # just use the first available nic
+        $PXE_NIC=$(ip link | awk -F: '$0 !~ "lo|vir|wl|^[^0-9]"{print $2;getline}' | head -n 1 | sed -e 's/^[[:space:]]*//')
+    fi
+
+    function net_pxe_ip {
+        net_pxe_addr=$(ip addr | awk "/inet / && /${PXE_NIC}/{print \$2; exit }")
+        echo $net_pxe_addr | awk -F '/' '{ print $1; exit }'
+    }
+    PXE_IP=$(net_pxe_ip)
+
+    if [ "x" == "x${PXE_IP}" ]; then
+        echo "Could not find IP for pxe to bind to"
+        exit 1
+    fi
     
     tee /tmp/pod-shared/conductor-local-ip.conf << EOF
     [DEFAULT]
